### ISSUE TITLE
Remove diacritics from Id's

### ISSUE THREAD

**Issue by benyrfg** [bryanbraun/anchorjs#138]
Hello,

is there some way how to remove/replace diacritics from the ID's? I'm trying make smooth scrolling to anchors from generated anchor links menu, but, probably, the diacritics is the problem.

For ex.: #dělám-jen-to-co-je-přirozené-a-co-mi-radí-instinkt

Thanks

**Comment by bryanbraun** [comment]
@benyrfg, there are [a few options](https://www.bryanbraun.com/anchorjs/#options) for customizing the generated IDs (like truncating them), but nothing for changing the diacritics.

The best way to take more control over the IDs being generated is to add your own IDs prior to running AnchorJS. If the elements already have IDs, then AnchorJS will just use them instead of generating new ones.

I'm not sure why diacritics would interfere with smooth scrolling... they should just be treated like any other unicode character. Maybe check to see if [your charset is set correctly](https://github.com/bryanbraun/anchorjs/issues/134#issuecomment-590439843)? 😕

**Comment by bramchi** [comment]
Great suggestion to prepare the IDs before anchorjs passes over them.

I was seeing very peculiar IDs being generated by anchorjs for a heading with text Checklist. 

```html
<h2 id="DeveloperDocumentation:GettingStarted-Checklist">Checklist</h2>
``` 

But setting the ID myself made the results by anchorjs predictable again. 

```html
<h2 id="checklist">Checklist</h2>
```

Lovely library!

**Comment by bryanbraun** [comment]
I'm going to go ahead and close this, as I think there's no action to be taken here, but let me know if you feel otherwise.
