### ISSUE TITLE
handle nbsp (nonbreaking space) in headings

### ISSUE THREAD

**Issue by zebapy** [bryanbraun/anchorjs#141]
Our site uses a plugin to prevent widows by adding a `&nbsp;` between the last 2 words of most elements (h1, p, etc). 

When using anchorjs, this is causing some headings to come out as 
```html
<h2 id="where-to&nbsp;start">Where to&nbsp;Start?
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#where-to&nbsp;start"></a>
</h2>
```

Everything is functional but the anchor link suffers in readability after.

**Comment by bryanbraun** [comment]
@zebapy, I'm on board with this.

It's definitely an edge-case, but a good-enough solution seems pretty low-overhead and straightforward.

As for the approach, [he](https://github.com/mathiasbynens/he) looks nice but I want to keep anchorjs dependency-free. I like the simplicity of [the textarea approach](https://stackoverflow.com/a/7394787/1154642). It shouldn't be hard to add it at the beginning of [our urlify function](https://github.com/mathiasbynens/he), and add a test for it.

The biggest downside of this change is that it would require a major version bump, since we could be potentially changing link locations for existing users. I'm ok with that, but if I'm doing a major version bump, I want to include https://github.com/bryanbraun/anchorjs/issues/109 in it as well.

Feel free to submit a PR if you want to take a pass at this. Otherwise, I'll get to it eventually.

**Comment by zebapy** [comment]
I'm also encountering curly quotes and degree icons not being replaced with nothing. `#there’s-a-heading-after-intro-360°-degrees`

**Comment by bryanbraun** [comment]
@zebapy, the quotes and degree icons are a part of the decision to support UTF-8 characters (except for [a small set of non-safe characters](https://github.com/bryanbraun/anchorjs/blob/261c6d3e5013cc82a7682e427378f1dd89d8456d/anchor.js#L235-L236)). I had originally stripped out these kinds of characters, but I changed the approach in order to better support international characters. For more background on that decision, see: https://github.com/bryanbraun/anchorjs/issues/41

The `&nbsp` showing up is different to me, since that's not an instance of a UTF-8 character, and I don't know of anybody who would want to see those in their urls. 😄
