### ISSUE TITLE
'touch' detection is invalid

### ISSUE THREAD

**Issue by nichoth** [bryanbraun/anchorjs#188]
Using this on a laptop computer, and I have set
```js
            anchors.options = {
                visible: 'touch'
            }
```

However, it is detecting that a laptop is a touch device. When I look at the source code and try some in the browser console, `!!window.TouchEvent` is returning true, which is here in the source code — https://github.com/bryanbraun/anchorjs/blob/master/anchor.js#L52

------------

example in use: https://nichoth.com/list/

**Comment by bryanbraun** [comment]
Thanks for the issue and PR. I hope to be able to take a closer look at this next week. 👍

**Comment by y377** [comment]
For such an excellent plugin, I would like to share my [demo](https://beep.vip/2021/12/12/pt/#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85), my touch can be used well! There are also hover prompts and one-click copy (he can jump to the anchor by clicking on it).

**Comment by bryanbraun** [comment]
Hey, @nichoth, thanks for reporting the issue.

This issue has come up before and been discussed in detail here: https://github.com/bryanbraun/anchorjs/issues/168

In short, your fix addresses some common device use-cases but breaks others because [there's no reliable way to detect a touchscreen](https://www.stucox.com/blog/you-cant-detect-a-touchscreen/). 😞 

Ultimately, this touch feature is misleading and I plan to remove it entirely in a future version of AnchorJS.

My recommendation is that if you want the older behavior of this, you can [use version 4.2.2 as described here](https://github.com/bryanbraun/anchorjs/issues/168#issuecomment-1248632671).

**Comment by nichoth** [comment]
Ok thanks for checking it out. I am using my fork currently, and that has been working for me.
