### ISSUE TITLE
Consider adding a non-breaking space between element and anchor

### ISSUE THREAD

**Issue by chauncey-garrett** [bryanbraun/anchorjs#31]
A non-breaking space is necessary to prevent orphaned anchors:

![screen shot 2015-03-27 at 13 37 49](https://cloud.githubusercontent.com/assets/302358/6874635/c814f0b4-d486-11e4-9e78-90bf6f32f65f.PNG)

This creates a space that is visually unappealing while the anchor is hidden:

![2015-03-27 at 13 40](https://cloud.githubusercontent.com/assets/302358/6874653/fd6bb338-d486-11e4-8a1d-e1e8ded608be.png)

**Comment by bryanbraun** [comment]
@chauncey-garrett, thanks for reporting this, and for the screenshots. This looks like an issue that should be fixed but I haven't been able to reproduce it yet. In the instances on my [example page](http://bryanbraun.github.io/anchorjs/), the links already act like non-breaking spaces (you can test it by using the inspector to reduce the width of the `.main` section until you'd expect to see the anchor break onto a new line by itself (which never happens for me).

Perhaps you're seeing the issue because your titles already have space at the end of them? If not, maybe can you demonstrate it using something like [Codepen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) (and the [CDN version of AnchorJS](https://cdnjs.com/libraries/anchor-js))?

**Comment by chauncey-garrett** [comment]
@bryanbraun thanks for getting back to me. At this point, I'm not seeing the issue on my site anymore. I'm not quite sure what caused it, when it broke, or when I fixed it so I'm afraid that both the good and bad news is there's nothing more to do here! Most likely there must've been something on my end that caused this issue.

Thanks again!

**Comment by bryanbraun** [comment]
Ok. Feel free to reopen if you can reproduce the issue.

**Comment by lkraav** [comment]
(3.2.2)

It seems to be happening to me.
![screenshot_2018-07-15 woocommerce plm group russia wordpress](https://user-images.githubusercontent.com/147228/42892625-ecd9f46a-8aba-11e8-9e59-5a2e549a26c1.png)

Testing update to 4.1.1 now.
