### ISSUE TITLE
Not working if scripts are included in <head>

### ISSUE THREAD

**Issue by Fastidious** [bryanbraun/anchorjs#40]
Anchors are not showing, what could the issue be? I have the minimized version added, and:

```
<script>
anchors.options = {
  visible: 'always',
  icon: '❡'
};
anchors.add('p');
</script>
```

**Comment by Fastidious** [comment]
Found the problem. It will not work if scripts are on `<head>`, but works fine it there are anywhere else.

**Comment by bryanbraun** [comment]
Interesting. I'm still curious as to why scripts won't run in `<head>`. Seems like that ought to be addressed.

Do you know if it only happens for inline scripts?

**Comment by Fastidious** [comment]
@bryanbraun I have another inline script ([highlightjs](https://highlightjs.org)), and it works fine. If it helps, the site I have anchorjs running right now is my [weblog](https://collantes.us/).

**Comment by bryanbraun** [comment]
I'll leave this issue open until I can confirm whether or not this is an AnchorJS-specific issue. If it is, we'll want to address it. Leaving it open will also help others find the issue, if it's happening to them.

It's [a good performance practice to run blocking scripts at the end of the body](https://developer.yahoo.com/performance/rules.html#js_bottom=), so I'm not considering this a huge priority right now. If others are running into it, I'll reevaluate.

**Comment by bryanbraun** [comment]
I looked into this a bit more. There's no issue with loading anchor.js in the head. You just have to be careful not to run `anchors.add()` before the DOM is loaded, otherwise it won't find any elements for the selector you passed in.

This isn't an anchorjs issue, so much as something you always need to watch out for when you are loading javascript that interacts with the DOM.

There's a few ways to avoid this:
* Put the code running `anchors.add` at the end of the body tag.
* Ensure that the code is placed inside a `$(document).ready` function (or equivalent).
