### ISSUE TITLE
Expose Anchored Elements list

### ISSUE THREAD

**Issue by OleVik** [bryanbraun/anchorjs#50]
Is there a way to access the `anchors`-object in order to retrieve the elements which have an added anchor? That is, I need to retrieve the list of header-elements which are set through `var anchors = new AnchorJS()` to iterate over them and generate a simple Table of Contents list in html.

**Comment by bryanbraun** [comment]
@OleVik, currently there isn't, but I kind of like that idea. It seems like a fairly simple change to keep those elements on the object instead of having them fall out of scope.

For the record, I don't want to add a Table of Contents feature to AnchorJS (to keep it simple and lightweight) but keeping the element list around for external scripts to access has few downsides.

**Comment by OleVik** [comment]
That was my thought too, access to the element list could easily churn out a Table of Contents or similar, without needing substantial modification to AnchorJs itself.

**Comment by bryanbraun** [comment]
Hey, @OleVik, I've got [a PR](https://github.com/bryanbraun/anchorjs/pull/53) up that addresses this issue. Mind taking a look and providing feedback?

**Comment by OleVik** [comment]
Tested it now, works marvelously - even with very long headers. Thanks for putting it together, it's a great addition.
