### ISSUE TITLE
Remove CSS Cruft

### ISSUE THREAD

**Issue by joeyhoer** [bryanbraun/anchorjs#64]
It's trivial to style the anchor links with CSS with more control:

```
.anchorjs-link {
  text-decoration: none;
  opacity: 0;
  padding-left: 0.35em;
}

.anchorjs-link::after {
  content: '#';
}

*:hover > .anchorjs-link,
.anchorjs-link:focus {
  opacity: 1;
}
```

The size of the script can be reduced by 57% (minified gzipped) by removing the embedded CSS, font family, and touch detection.

**Comment by bryanbraun** [comment]
It's a reasonable approach to separate the CSS and JS and have the implementer customize the CSS however they want. It's the approach I used for the first 6 months of this project.

And saving 57% sounds like a lot, but to be clear, the difference you're talking about it is 1.4K. 57% of a small number is a small number.

The reason I switched to embedded styles for 1.0, was because it brought a lot of benefits. It put all configuration in one place, reduced it to a single include, and made it into a module that people didn't have to fork, patch, or edit to use.

Now there's a case to be made for keeping the embedded css, but just removing the font-family. The encoded font-family for that default anchor link alone is 1K. But almost everybody who uses AnchorJS uses the link icon that comes with that font-family. All the projects on the "Used by" section of the docs, use it, and it's rare for me to stumble across a project that doesn't. Maybe that's because it's default, but I'm hesitant to change a default that's working so well for people.

If you want to go with the non-embedded CSS/Font approach and customize the CSS to save 1.5K, you can still use AnchorJS 0.4. [The branch](https://github.com/bryanbraun/anchorjs/tree/0.4.x) is still on github and you can [download it here](https://github.com/bryanbraun/anchorjs/archive/0.4.x.zip).

**Comment by joeyhoer** [comment]
I understand your logic, and respect your reasoning. It's particularly difficult to walk back this decision now that you have a wide user base.

I personally like the methodology adopted by other small libraries like [headroom.js](https://github.com/WickyNilliams/headroom.js) where "**you must supply your own CSS styles separately.**"

If anyone else is interested in following this issue, I've updated [the `master` branch of my fork](https://github.com/joeyhoer/anchorjs/tree/master/) to remove the CSS, along with some other, minor, modifications. Of course, this isn't a particularly challenging change to make; it just offers a different take on the library.

**Comment by bryanbraun** [comment]
Sounds good. I'm glad you brought this up and that you've got a branch working for you. If I find anybody else interested in the supply-your-own-CSS approach, or pushing to reduce the filesize, I'll direct them to this issue, and your forked version. 👍
