### ISSUE TITLE
Support scoping new instance to given DOM element.

### ISSUE THREAD

**Issue by adjohnson916** [bryanbraun/anchorjs#66]
Hi, I'd like to create an instance of AnchorJS that's scoped to a given DOM element, so that the selector (default or otherwise) doesn't affect the whole document. Let me know you want a PR.

**Comment by bryanbraun** [comment]
@adjohnson916, have you tried getting an instance with `new AnchorJS()` and scoping its influence via the CSS selector [as described here](http://bryanbraun.github.io/anchorjs/#multiple-sets-of-anchors)?

**Comment by adjohnson916** [comment]
@bryanbraun Yes, that's what I'm doing now, but it'd be convenient to not have to prefix every selector so we could e.g. use the defaults, or at least a more terse custom list.

**Comment by bryanbraun** [comment]
Gotcha.

I see what you're saying. For the sake of simplicity (both api simplicity and code simplicity) I think I'd rather keep all the querySelectors global. I'm trying to be careful about adding functionality that doesn't meet the 80% usecase, especially when it's possible to solve the problem with existing features. If the PR made anchorjs MORE lightweight, I'd consider it, otherwise I'd rather keep it as-is.

**Comment by adjohnson916** [comment]
@bryanbraun This does would it more lightweight in terms of performance, but agreed, not in terms of options/features.
