### ISSUE TITLE
touch detection fails

### ISSUE THREAD

**Issue by djmitche** [bryanbraun/anchorjs#85]
When `anchor.options.visible == "touch"`, the anchors always appear for me.

I'm using Firefox release (52.0) on a hidpi Carbon X1 that does not have a touchscreen (but such a screen is an option on X1s..)

The issue seems to be this:

```
>> window.ontouchstart
<- null
```
which is to say, the property exists but is null.  A quick skim of the MDN docs doesn't tell me why that would be the case.

In taskcluster/taskcluster-docs#177 I fixed this by just distinguishing the `null` from a missing property.

**Comment by bryanbraun** [comment]
Thanks for bringing this to my attention.

You are right that AnchorJS isn't detecting the touchscreen accurately. I've been mimicking [Modernizr's checks here](https://github.com/Modernizr/Modernizr/blob/da22eb27631fc4957f67607fe6042e85c0a84656/feature-detects/touchevents.js#L40), and they're taking a stance that they'll only detect the Touch API, because trying to detect touch-devices with 100% accuracy [is impossible](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/). I do the same thing because it gets pretty close. The device you're talking about appears to be an edge case. I should document this "pretty close" caveaut more clearly in both the docs and my function names (`this.isTouchDevice` implies that I'm trying to detect all touch devices 😓 ).

As for your specific case, your browser appears to support touch events, but not a touch screen. I believe the reason it's returning `null` is because no `ontouchstart` events have been set on the `window`. Likewise, if you check `window.onclick` in Firefox it will also return `null` until you set an event to it:

```
>> window.onclick
<- null
>> window.onclick = function() { console.log('you clicked'); };
<- function () { console.log('you clicked'); }
# (Click on the window)
<- "you clicked"
```

If I was to add that `!== null` check to anchorJS, it could cause problems because touch-devices _not_ using that event would have their anchor links hidden (and thus wouldn't be able to click them).

I'd much rather have links visible on a non-touch devices (as is your case) than no links visible on a touch-only device.

**Comment by djmitche** [comment]
Oh, good point -- I thought that ontouchevent was supposed to be a function (`window.ontouchevent(function(e) { .. })`) but that's not the case.  Oh well.
