### ISSUE TITLE
Is it possible to add an offset above the section?

### ISSUE THREAD

**Issue by JacobLett** [bryanbraun/anchorjs#89]
I have a sticky top navigation and would like to add some space above the section when it is clicked.

**Comment by bryanbraun** [comment]
@JacobLett, there's a couple of ways you could do this:

1. You could add padding to the top of your headings equal to the height of the fixed heading, [like this example on Codepen](https://codepen.io/bryanbraun/pen/PjRPGx?editors=1100).
2. You could use [Section IDs and `data-anchor-id`](https://www.bryanbraun.com/anchorjs/#section-ids), so that linking to a heading jumps to a wrapper section, which has extra padding on it.
3. Or you could use that `data-anchor-id` feature to link to some hidden element positioned that you position above your headings (like an absolutely positioned span or something).

Either way, I'd encourage you to work towards a CSS-based solution if you can.

**Comment by JacobLett** [comment]
Thank you for your reply and help Bryan.

**Comment by stephenbe** [comment]
@bryanbraun Hi Bryan, little question about this, would it be possible for Anchor to add an option to do this without knowing the id. 

Because anchor adds the ids automatically, I can't use  data-anchor-id effectively.

Something like this : 
```
<h1>
  <span class="absolute-offset" data-anchor-id="true"></span>
 My h1 title
</h1>
```

It would become  : 
```
<h1>
  <span class="absolute-offset" data-anchor-id="true" id="my-h1-title"></span>
  My h1 title
</h1>
```

Thanks!

**Comment by bryanbraun** [comment]
Hey @stephenbe 👋.

I added [some docs for working around sticky headers](https://www.bryanbraun.com/anchorjs/#pages-with-a-sticky-navbar). Here's [an example implementation using Codepen](https://codepen.io/bryanbraun/pen/BvJwZJ?editors=1100).

My current recommendation is to use CSS with the :target pseudo-selector for sticky headers, since the `data-anchor-id` is more for enabling [highlighted sections](https://css-tricks.com/on-target).

Does that help with your situation?
