### ISSUE TITLE
Separate js and css

### ISSUE THREAD

**Issue by denar90** [bryanbraun/anchorjs#91]
Hi there :)
I wanted to ask the purpose of having css in js file. 
The problem I faced is control of loading resource. I wanna defer js resource but it causes longer Time to interactive because of additional browser work like networking/layouting . What is really nice to have is separated css file with all styling and stuff which users can include in bundle/ preload etc, so the user they have more control of it.
Thanks)

**Comment by bryanbraun** [comment]
@denar90, that's a good question.

Having CSS managed in the JS was a choice I made a while back, mostly to make it more simple to implement AnchorJS. [Earlier versions of AnchorJS](https://github.com/bryanbraun/anchorjs/tree/0.4.0) actually came with all the styles in a separate `anchor.css` stylesheet, which I've since moved away from.

I wouldn't recommend deferring the loading of AnchorJS, as that could make it so the anchors aren't on the page in time for some browsers to jump to the link. See details [here](https://www.bryanbraun.com/anchorjs/#dont-run-it-too-late) and [here](https://github.com/bryanbraun/anchorjs/issues/69#issuecomment-246867707).

So I appreciate the PR, but I'm not looking into splitting the CSS back out again. If you have other thoughts on how to give users more control or improve performance within the existing CSS approach, let me know.

**Comment by bryanbraun** [comment]
I'm going to go ahead and close this issue, for the reasons mentioned above. You're always free to use the `0.4.0` version of AnchorJS which had the the styles separated out, if you'd like.

**Comment by denar90** [comment]
Sorry, totally missed your comment. Thanks for looking into this issue and explaining stuff.

**Comment by bryanbraun** [comment]
This is late, but I just remembered that there's a fork of this project that separates the CSS you might be interested in. See this other issue for details: https://github.com/bryanbraun/anchorjs/issues/64

I just wanted to leave a note in case anybody else comes across this issue looking for something like this.
