### ISSUE TITLE
Anchorjs hexo plugin

### ISSUE THREAD

**Issue by noraj** [bryanbraun/anchorjs#93]
Hi, thank you for this awesome tool.
Can you create an anchorjs [hexo plugin](https://hexo.io/docs/plugins.html): it sound super easy but I'm not a JS guy. Plus it will be better if you are the official author of the plugin.
If you have time someday it can be awesome.

**Comment by bryanbraun** [comment]
@noraj1337, I'd like to see a plugin like this but I can't really dedicate the time to building and maintaining it. I'm afraid that if I built it, I'd end up neglecting it (especially since [my personal site](https://bryanbraun.com) runs on Jekyll, not Hexo 😛).

That being said, I'll leave this issue open for a while in case anybody else want's to build a plugin like this, (or, if anybody knows of an existing Hexo plugin for this, feel free to post it below).

**Comment by bryanbraun** [comment]
I'm going to go ahead and close this. People can still add comments below if they have found (or created) a Hexo plugin worth recommending. 👍
