### ISSUE TITLE
Anchors for nested list items

### ISSUE THREAD

**Issue by pauloue** [bryanbraun/anchorjs#95]
When a list item has children and right-side anchors are used, the anchor gets placed on a new line after all the children. Left-side anchors work, but they appear on top of the bullet points. Is there any way to fix this so that the anchors are always at the end of the line of text?

Example:

![2018-07-10-214824_swaygrab](https://user-images.githubusercontent.com/21223385/42546420-4e83c3b6-848b-11e8-8528-52639bbce4af.png)

**Comment by bryanbraun** [comment]
Hey @pauloue 👋.

I was looking into this today. ([Here's a demo I put together.](https://jsfiddle.net/urk2z3hp/))

I wasn't able to replicate the newline issue, so I think that might be caused by something in your markup or content. I could see this being caused by an editor importing carriage return characters or something like that.

As for the overlapping bullets, my recommendation for that is for you to write some custom CSS that overrides the styles to make them look the way you want. I _could_ add styles like these to the plugin but 1) it feels like an edge case and 2) the ideal styles depend on the site (some people place their bullets close to the list items, others far away, etc).

**Comment by pauloue** [comment]
Your demo doesn't have any nested lists. Here's an updated version with the issue: https://jsfiddle.net/urk2z3hp/19/.

It works correctly if the closing list item tag goes on the same line instead of after the nested list, but apparently the `<ul>` is supposed to be a child of the `<li>`: https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list.

If this can't be fixed, your CSS fix for the overlapping bullets is helpful.

**Comment by bryanbraun** [comment]
Oh I see your point, on the nested `<li>`s. 

Yeah, that's an interesting case. I was hoping we could tweak our selector to handle those `<li>`s differently, but it surprisingly can't be done (until there's support for [the :has() pseudo-selector](https://caniuse.com/#search=%3Ahas)).

My recommendation for now would be to position the anchors to the left using a CSS style override like the ones I demonstrated:

![image](https://user-images.githubusercontent.com/1256329/43677593-7a5d23d8-97d2-11e8-96a5-5f37397c8339.png)

(you could also use CSS to replace the bullets themselves with link icons, if you prefer how that looks)
