### ISSUE TITLE
Require.js: Uncaught ReferenceError: achors is not defined

### ISSUE THREAD

**Issue by stephenbe** [bryanbraun/anchorjs#96]
Hello,
I'm getting this error while trying to impliment with requireJS : 
“Uncaught ReferenceError: anchors is not defined”

May I know if you have any clue on this?

**Comment by bryanbraun** [comment]
Hey @stephenbe. 👋 

This looks like the kind of error you get when the `anchors` object hasn't been created yet (or perhaps it _has_ been created, but it doesn't exist in the scope you are calling it from).

If you are using requireJS, you need to require anchor-js and create your own instance of "anchors" manually ([as described in the docs](https://www.bryanbraun.com/anchorjs/#installation) around commonjs usage). It might look something like this:

```js
var anchorJS = require('anchor-js');
var anchors = new anchorJS();

anchors.add('h1, h2, h3');
```

Does that help? I'd have to see an example in order to help debug any further.

**Comment by bryanbraun** [comment]
I'm going to go ahead and close this since I haven't been able to replicate it. Let me know if this is still an issue after the suggestions I made. 👍

**Comment by stephenbe** [comment]
Hey @bryanbraun ,

I am so sorry for taking this long to respond to you. Thank you so much for your help. I indeed just needed to require it and it worked beautifully.

Thank you so much. Again, sorry for taking so long and thank you for your patience.
